### ISSUE TITLE
Change default style

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-messages#5]
Current styles

![screen shot 2015-03-30 at 07 59 32](https://cloud.githubusercontent.com/assets/157534/6890827/c289f4c2-d6b2-11e4-8d63-ba333a210ded.png)

jsbin: http://jsbin.com/tudegi/1/edit

Here is what I propose

![screen shot 2015-03-30 at 08 28 45](https://cloud.githubusercontent.com/assets/157534/6891086/d1cbaf26-d6b6-11e4-977a-3db558f4c50e.png)

jsbin with comments: 

http://jsbin.com/tudegi/1/edit

Note: I would go for adding a space between plugin name and filename.

``` css
/*
 * /!\ statement added by postcss-messages
 */
body:before {
  display: block;

  /* not a problem for old browsers, box will still be on top of body */
  position: fixed;
  top: 0;
  left: 0;
  right: 0;

  font-size: .9em;
  padding: 1.5em 1em 1.5em 4.5em; /* padding + background image padding */

  color: white;
  background: #DF4F5E;
  background:
    /* icon: svg inlined from iconmonster
     * I just added a fill color by hand on the <path> (#A82734)
     *  (encodeURIComponent({ svgcontent without prologue and doctype }))
     * for automation, see https://github.com/filamentgroup/directory-encoder/blob/master/lib/svg-uri-encoder.js 
     */
    url("data:image/svg+xml;charset=utf-8,%3Csvg%20version%3D%221.1%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20xmlns%3Axlink%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink%22%20x%3D%220px%22%20y%3D%220px%22%20width%3D%2248px%22%20height%3D%2248px%22%20viewBox%3D%220%200%20512%20512%22%20enable-background%3D%22new%200%200%20512%20512%22%20xml%3Aspace%3D%22preserve%22%3E%3Cpath%20fill%3D%22%23A82734%22%20id%3D%22warning-4-icon%22%20d%3D%22M228.55%2C134.812h54.9v166.5h-54.9V134.812z%20M256%2C385.188c-16.362%2C0-29.626-13.264-29.626-29.625c0-16.362%2C13.264-29.627%2C29.626-29.627c16.361%2C0%2C29.625%2C13.265%2C29.625%2C29.627C285.625%2C371.924%2C272.361%2C385.188%2C256%2C385.188z%20M256%2C90c91.742%2C0%2C166%2C74.245%2C166%2C166c0%2C91.741-74.245%2C166-166%2C166c-91.742%2C0-166-74.245-166-166C90%2C164.259%2C164.245%2C90%2C256%2C90z%20M256%2C50C142.229%2C50%2C50%2C142.229%2C50%2C256s92.229%2C206%2C206%2C206s206-92.229%2C206-206S369.771%2C50%2C256%2C50z%22%2F%3E%3C%2Fsvg%3E") .5em no-repeat,
    /* background */
    linear-gradient(#DF4F5E, #CE3741)
  ;

  /* sugar */
  border: 1px solid #C64F4B;
  border-radius: 3px;
  box-shadow: inset 0 1px 0 #EB8A93, 0 0 .3em rgba(0,0,0, .5);

  /* nice font */
  white-space: pre;
  font-family: Menlo, Monaco, monospace;
  text-shadow: 0 1px #A82734;

  /* the content */
  content: "other-plugin: a.css:10:4: Here is some warning from other plugin"
}
```
